### ISSUE TITLE
Support for MediaElement

### ISSUE THREAD

**Issue by WraithKenny** [awesomemotive/google-analytics-for-wordpress#11]
It'd be nice if the plugin handled adding the MediaElement.js Google Analytics plugin integration, if possible. The core repo has a [plugin]( https://github.com/johndyer/mediaelement/blob/master/src/js/mep-feature-googleanalytics.js) (which might need tweeking) but I don't think this is included in WordPress's version of Media Element.

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
