### ISSUE TITLE
Remove full URLs from gettext since there is no localized alternative

### ISSUE THREAD

**Issue by tacoverdo** [awesomemotive/google-analytics-for-wordpress#130]
In [this file](https://github.com/Yoast/google-analytics-for-wordpress/blob/trunk/admin/pages/settings.php) a couple of URLs are wrapped in gettexts. 

Since the URLs do not have a localized alternative, this can only cause problems when translating the strings. Please use [sprintf](http://php.net/manual/en/function.sprintf.php) to extract the URL from the gettext.

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
