### ISSUE TITLE
how to manually place the tracking code

### ISSUE THREAD

**Issue by ibes** [awesomemotive/google-analytics-for-wordpress#159]
It seems like the option to manually place the tracking code has disappeared from version 4 to version 5.

This breaks my analytics solution and I would like to have it back ;)

Is there a new way I haven't seen?

See: https://yoast.com/wordpress/plugins/google-analytics/manual-placement/

**Comment by jbeales** [comment]
I would like some control over where the code is output in wp_head. At the moment it's coming out between the `<link>` tags for CSS and the external `<script>` tags, which Google's PageSpeed is complaining about:

> The following inline script blocks were found in http://www.example.com/ between an external CSS file and another resource. To allow parallel downloading, move the inline script before the external CSS file, or after the next resource.

I realize that this might make much different in real-world performance, bit sometimes I get paid to improve benchmarks.

In my case making the priority filterable in the [`add_action( 'wp_head', ....)` call](https://github.com/Yoast/google-analytics-for-wordpress/blob/trunk/frontend/abstract-class-tracking.php#L74) would let me place the tracking code either further up or down in the HTML.

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
