### ISSUE TITLE
Disable tracking for super admins on multisite

### ISSUE THREAD

**Issue by wpperform** [awesomemotive/google-analytics-for-wordpress#175]
Posted the same issue before as https://github.com/Yoast/google-analytics-for-wordpress/issues/138
Was closed as relating to https://github.com/Yoast/google-analytics-for-wordpress/issues/162, which was fixed in ver 5.1.4.  Unfortunately, 5.1.4 doesn't fix the original issue we reported, so here it is again, along with a tested fix:

The do_tracking() function in class-frontend.php doesn't seem to allow disabling tracking when a super admin is logged in and viewing a site on which he isn't a user.

Adding the code below around line 42 of class-frontend.php turns off tracking for super admins and has the advantage of not requiring users to update options.

if ( is_super_admin() ) {
return false;
}

**Comment by Petervw** [comment]
Fixed in #326

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
