### ISSUE TITLE
Add newline after GA tracking code

### ISSUE THREAD

**Issue by tacoverdo** [awesomemotive/google-analytics-for-wordpress#253]
Improve readability of the source code by adding a newline after `<!-- / Yoast Google Analytics -->`.
![view-source_https___yoast_com](https://cloud.githubusercontent.com/assets/5147598/5501338/6044d37a-8759-11e4-9433-db06a24deabc.png)

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
