### ISSUE TITLE
Double page anchor in URL after saving

### ISSUE THREAD

**Issue by GaryJones** [awesomemotive/google-analytics-for-wordpress#259]
After saving, WP adds a `#top` to the URL so that the user sees the "Settings saved." message. However, GAFW also adds a `#general` anchor so that the user is returned to the first tab. This is an invalid URL. What it does is make the tab links also have the `#top` prefix, resulting in errors such as:

> Bad value `#top#customdimensions` for attribute `href` on element `a`: Illegal character in fragment: not a URL code point.

**Comment by Rarst** [comment]
I have tried to simply remove the `#top` part from links, but it makes result "jumpy" with page rapidly moving to a point below tabs on switch. 

This might need to be adjusted on JS level. Anyone knows on top of their head what script is implementing the tab switching there? :)

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
