### ISSUE TITLE
Recurrent HTTP requests in admin area again

### ISSUE THREAD

**Issue by Rarst** [awesomemotive/google-analytics-for-wordpress#261]
Seeing POST HTTP request on every load admin-side again, after updating to 5.2.7.

URL: `https://accounts.google.com/o/oauth2/token`

Call stack:

WP_Http->request()
WP_Http->post()
wp_remote_post()
Yoast_Google_WPIO->makeRequest()
Yoast_Google_OAuth2->refreshTokenRequest()
Yoast_Google_OAuth2->refreshToken()
Yoast_Google_Client->refreshToken()
Yoast_Google_Analytics_Client->refresh_tokens()
Yoast_Google_Analytics_Client->__construct()
Yoast_Google_Analytics->set_client()
Yoast_Google_Analytics->__construct()
Yoast_Google_Analytics::get_instance()
Yoast_GA_Dashboards_Api_Options->set_options()
Yoast_GA_Dashboards_Api_Options->__construct()
Yoast_GA_Dashboards_Api_Options::get_instance()
Yoast_GA_Dashboards_Collector->__construct()
Yoast_GA_Dashboards->init_dashboards()
Yoast_GA_Admin->init_settings()
do_action('admin_init')

Stepping through the code this here https://github.com/Yoast/api-libs/blob/master/googleanalytics/class-google-analytics-client.php#L68-L74 seems to expect return from `refresh_token()` method that has no return.

**Comment by drewhammond** [comment]
Bump for this

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
