### ISSUE TITLE
 Forcing Display all errors. Version 5.2.8

### ISSUE THREAD

**Issue by puckettventures** [awesomemotive/google-analytics-for-wordpress#291]
When I installed GA by Yoast on my new site. I noticed that no matter what the debug settings say in the plugin, it always forces display errors in php. I searched for the word debug throughout the plugin code and all the lines seem to be correct. I also looked for error_reporting, display_errors which I found no instances. 

I tried several fresh installs. Any thoughts?

![support1](https://cloud.githubusercontent.com/assets/6002306/5778605/8c506e8a-9d6a-11e4-8827-2981e4ae3110.png)
![support2](https://cloud.githubusercontent.com/assets/6002306/5778610/90c77d82-9d6a-11e4-9ea2-f3732d926071.png)

**Comment by CarolineGeven** [comment]
The debug information gets turned on (and off) in your wp-config.php file and not in our plugin. Please look into the wp-config.php file of your install to solve this.

**Comment by puckettventures** [comment]
Debug is not on in wp-config. These warnings only show when the yoast plug
in is activated.

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
