### ISSUE TITLE
Internal links being tracked in outbound-widget-int

### ISSUE THREAD

**Issue by samteezy** [awesomemotive/google-analytics-for-wordpress#294]
I don't know if this is related to existing issues regarding outbound-article-int, so I wanted to double-check by posting this issue.

I am seeing nearly all internal clicks on my site show in outbound-widget-int. I don't have an option to track internal links as outgoing enabled, so I'm not sure if this is an intended result.

**Comment by CarolineGeven** [comment]
Unfortunately, this is not a bug, but a support request. We use GitHub exclusively for (well-documented) bug reports, so we cannot help you here.

To receive free support for WordPress SEO we have the following channels:
* [Yoast Knowledge base](http://kb.yoast.com)
* [Support forums](https://wordpress.org/support/plugin/wordpress-seo) on WordPress.org

Or if you want personal support via email, you can purchase [WordPress SEO Premium](https://yoast.com/wordpress/plugins/seo-premium/).

Thanks for your understanding.

**Comment by CarolineGeven** [comment]
Thanks for reporting this issue. 
Unfortunately we do not have enough information to reproduce this problem. Please answer the following questions so we can try to figure out what is going on and help us reproduce it.

* What version of WordPress are you running?
* What version of PHP are you running?
* What kind of webserver are you running (Apache, Nginx,IIS)?
* Are you running the latest version of the plugin?
* Do you still have this issue if you switch to the default WordPress theme (*e.g. Twenty Fourteen*) and deactivate all other plugins?

Also, it will help us a lot if you can provide a backtrace of the error encountered. [This gist](https://gist.github.com/jrfnl/5925642) will explain how to enable the backtrace in your website: https://gist.github.com/jrfnl/5925642

Thank you.

**Comment by samteezy** [comment]
1. 4.1
2. 5.3.29
3. Apache
4. Yes.
5. I'm not in the position to switch out the theme on this active site. We are using a custom-built theme.

I've attempted to run backtraces for you all in the past but could never seem to get it to work properly. I may try again in the next couple days.

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
