### ISSUE TITLE
Upgraded Yoast settings tabs are missing

### ISSUE THREAD

**Issue by blacknell** [awesomemotive/google-analytics-for-wordpress#307]
I've upgraded from an earlier 5.x release to the latest today, but the forms underneath the settings tabs are missing. I've uninstalled completely, checked the plugins files have actually gone and then reinstalled.

![screen shot 2015-02-08 at 21 55 23](https://cloud.githubusercontent.com/assets/8863732/6098624/3c88d02e-afdd-11e4-8f88-1ea7b831ef82.png)

**Comment by blacknell** [comment]
I noticed this error in the console from the dashboard min js file

TypeError: jQuery(...).yoast_ga_graph is not a function

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
