### ISSUE TITLE
Add option for siteSpeedSampleRate

### ISSUE THREAD

**Issue by hectorlee** [awesomemotive/google-analytics-for-wordpress#316]
Could we have an option to modify the siteSpeedSampleRate? It appears with the Universal Analytics the only way is to modify the create method which only the plugin creates. From what I've read is that this mod is important for low traffic sites since the default only samples 1% of traffic. Low traffic site might not get data at all without this mod. Thanks for much for reading this email.

https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#siteSpeedSampleRate

**Comment by lkraav** [comment]
+1 to this. Just noticed it myself, glad to find an open issue. I guess a pull request wouldn't hurt, but I have no time to juggle that for a month or so.

**Comment by lkraav** [comment]
Ping. This probably needs an outside pull request.

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
