### ISSUE TITLE
Google Analytics plug-in breaks image upload

### ISSUE THREAD

**Issue by shawntempesta** [awesomemotive/google-analytics-for-wordpress#320]
After an issue where when trying to upload an image in a post, you receive the error: "An error occurred in the upload. Please try again later.".

Upon investigating and deactivating one plug-in at a time, image upload started to work again after Google Analytics by Yoast was deactivated.

A list of other plug-ins includes: "Advanced Custom Fields", "Ajax Comment Posting", "Akismet", "Captcha", "Contact Form 7", "Easy Facebook Like Box", "Hello Dolly", "Jetpack by Wordpress", "Recent Tweets Widget", "Revolution Slider", "W3 Total Cache", "Wordpress Importer", "WP-PageNavi", "WP-Paginate" and "WP E-Signature".

Running the latest version of Wordpress, version 4.1.1.

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
