### ISSUE TITLE
Google Analytics doesn't track URL's of outbound clicks

### ISSUE THREAD

**Issue by sboerrigter** [awesomemotive/google-analytics-for-wordpress#324]
I am trying to track outbound links with the Google Analytics plugin. To do this I have checked the "Track outbound click & downloads" option in the plugin settings. 

When I go to "Behavior > Events > Overview" Google Analytics I can see some event categories like "outbound-widget-int, outbound-article-int, outbound-article and download", but when I click on them there are no URL's of the outbound links. When I go to "Event actions" I see the URL where the event is triggered, but nog the URL of the outbound page. On the "Event label" screen I see the categories of the website, but also no URL's of outbound pages.

I have seen various posts where the URL's of outbound clicks are tracked in Google Analytics. Why isn't this working with the Google Analytics plugin? Is there a way to fix this issue? Or am I missing an important setting in Google Analytics?

I have also tried to follow the instructions on this page to track the URL's of outbound clicks, but this doesn't seem to do the trick either: https://support.google.com/analytics/answer/1136920?hl=en

I am currently using: WordPress 4.1.1 and Google Analytics 5.2.8.

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
