### ISSUE TITLE
How to use this plugin on a development machine?

### ISSUE THREAD

**Issue by rodrigoprimo** [awesomemotive/google-analytics-for-wordpress#325]
I would like to use this plugin on my development machine connected with a test Google Analytics account I have to test future changes before publishing them on production.

As far as I know to be able to use Google Analytics with a local domain it is necessary to add the option 'cookieDomain': 'none' as explained in the link below:

https://developers.google.com/analytics/devguides/collection/analyticsjs/advanced#localhost

I couldn't find anything in the plugin interface to do that. I'm missing something? If not, have you ever considered adding this as a new option?

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
