### ISSUE TITLE
Event Tracking Reported Lower Than Expected

### ISSUE THREAD

**Issue by davidtzvi** [awesomemotive/google-analytics-for-wordpress#333]
Hi there,

I am using event tracking to track outbound clicks. The clicks reported in Analytics is substantially lower (sometimes over 30% discrepancy) than what the receiving sites are reporting in their stats. When I view the source of the links when not logged in as an admin, the event tracking looks intact and correct. Any ideas what may be causing this?

David

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
