### ISSUE TITLE
Links in Shortcode Output Not Filtered for Event Tracking

### ISSUE THREAD

**Issue by mrwweb** [awesomemotive/google-analytics-for-wordpress#334]
I don't know if there's a possible solution but I just ran into an issue where I thought I was tracking links output by a shortcode. I wasn't.

It seems that  shortcode output doesn't get filtered  by `output_parse_link`. I solved the issue by adding `apply_filters( 'the_content', $shortcode_output )` into my shortcode but that requires specific shortcodes to handle it rather than the plugin just working.

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
