### ISSUE TITLE
A few minor things

### ISSUE THREAD

**Issue by paaljoachim** [awesomemotive/google-analytics-for-wordpress#337]
Hey

It can be somewhat difficult in clicking the links in the tooltips. A more flexibility in area would be nice so the tooltip stays in place further.
Hovering over the Dashboard -> Sessions Q tooltip it begins below the black admin bar. If you turn up the Z index in the CSS it will hopefully go above the admin bar.
![screen shot 2015-03-20 at 23 37 34](https://cloud.githubusercontent.com/assets/5323259/6762053/79064abc-cf5a-11e4-815e-7fa5fd1e6501.png)

In General Settings -> Ignore users: what about including administrator in addition to Editor by default?
What about giving a message asking the user if the plugin can allow tracking of anonymous data?

Is there a tips/guide someplace on how to use the plugin in the best possible way?

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
