### ISSUE TITLE
Add analytics tab in WP SEO Metabox

### ISSUE THREAD

**Issue by omarreiss** [awesomemotive/google-analytics-for-wordpress#354]
In the WP SEO Metabox we should add a tab "Analytics". If GA by Yoast is installed, this should give info about the current page's stats (loaded with AJAX on clicking of the tab). If it's not installed, it should show a notice to install GA by Yoast.

**Comment by omarreiss** [comment]
Tab should contain:
* Top ten referrals
* Pie chart showing medium

**Comment by andylepp** [comment]
I agree this is a good idea

**Comment by Petervw** [comment]
Functionality:
If the Google analytics plugin is active, any user of Yoast SEO with the “manage_options" capability we should see a new tab (with the title: “Analytics") with Google Analytics statistics in the Yoast SEO
Metabox. These statistics should be listed in the new tab:
 - [ ] Pageviews (Line chart)
 - [ ] Bouncerate (Line chart)
 - [ ] Top ten referrals (Sortable table)
 - [ ] Medium/Source (Pie chart)
The static date range for these stats is yesterday, -1 month.

We’d like to have 4 small preview boxes with the stats above. Below the 4 small blocks with that data, we should see the full charts and data tables in detail. (See UI) The small blocks of data contain only the title and the value of that specific element.

Affected pages:
The Yoast SEO metabox is listed on the post add/edit screens.

UI:
We add a new tab on the metabox page with the title “Analytics”. The tab should have the following design:
+————————————————————+
| Pageviews | Bouncerate | Referrals | Source | 
+————————————————————+
| Chart Pageviews         |  Chart Bounce rate  |
+————————————————————+
| Table referrals             |  Pie Source              |
+————————————————————+

If the Google Analytics plugin is not active, or isn’t up to date (version > 5.5) we should show a message to the user with the following text and link to the Google Analytics repo to download the plugin:
“If you install our free Google Analytics by Yoast plugin, you’ll be able to instantly see your post’s analytics here, such as pageviews, bounce rate and more.”

If the User didn’t authenticate with Google Analytics and uses an up to date version (> 5.5) he should get the following warning on the Analytics tab (Use the “google-analytics-for-wordpress” text domain):
“We need you to authenticate with Google Analytics to use this functionality. If you set your UA-code manually, this won\'t work. You can %sauthenticate your Google Analytics profile here%s to enable dashboards."

Integration:
WP SEO contains the Analytics tab with a filter to provide a hook for the GA plugin. By default we show the message above, to push users to use the GA plugin.
GA by Yoast calls the registered filter in Yoast SEO to register the analytics charts. GA by Yoast will also handle the AJAX requests and fetch and store the data.

Data management:
If the user clicks on the “Analytics” tab, we should do an AJAX call. We ask for the most recent data for this post. If the data wasn’t cached in a transient, we should do an API call to Google and fetch the data. We need to store the data in a transient which is available for only 24 hours and after that we need to return the data in our AJAX call to the analytics tab.

If the data was already available in the transient, we need to check if the last day matches with the date of yesterday. If yesterday doesn’t exist in our dataset, we need to do the API call again and update the transient cache.

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
