### ISSUE TITLE
Plug SEO score with average loading time if GA is enabled

### ISSUE THREAD

**Issue by omarreiss** [awesomemotive/google-analytics-for-wordpress#366]
We can fetch the average loading time from GA if we have GA enabled. In WordPress SEO, we can take this into account for our scoring mechanism.

**Comment by omarreiss** [comment]
This is a good case for extending the Text analysis tool with an extra check. Let's see if we can do this as part of the js-seo audit.

**Comment by Rarst** [comment]
I remember loading times reported by GA to be quite... strange. If I remember right their sampling rates seem low, so results can be waaaay off on individual posts.

**Comment by omarreiss** [comment]
@Rarst yes I figured I need to do much more specification and requirements analysis for this. Thanks for the input!

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
