### ISSUE TITLE
Discuss: Create filter for changing the ability needed to edit the settings

### ISSUE THREAD

**Issue by omarreiss** [awesomemotive/google-analytics-for-wordpress#369]
We might want to allow users to make the GA settings available for capabilities lower than Admin.

**Comment by tacoverdo** [comment]
The same goes for the dashboard.

**Comment by lumpysimon** [comment]
+1 for individual filters on the user capability for the settings and dashboard pages. So I could do something like:

    add_filter( 'yoast_ga_settings_capability', 'my_ga_settings_capability' );
    add_filter( 'yoast_ga_dashboard_capability', 'my_ga_dashboard_capability' );

    function my_ga_settings_capability( $capability ) {
        return 'edit_others_posts';
    }

    function my_ga_dashboard_capability( $capability ) {
        return 'edit_posts';
    }

**Comment by monbauza** [comment]
+1 Please inform the customer of conversation # 77246 when this issue has been closed.

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
