### ISSUE TITLE
5.4: HTTP requests when dashboard disabled

### ISSUE THREAD

**Issue by ctalkington** [awesomemotive/google-analytics-for-wordpress#373]
I'm running a site with manual UA code and since the latest update to 5.4 it appears the issue of calling GA-API when no dashboard is in use is still occuring.

![image](https://cloud.githubusercontent.com/assets/209757/7240916/61dac948-e77a-11e4-9ae8-50785b0fdffd.png)

**Comment by ctalkington** [comment]
related #261 Yoast/api-libs#19

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
