### ISSUE TITLE
Analytics not recording session duration

### ISSUE THREAD

**Issue by meme123** [awesomemotive/google-analytics-for-wordpress#382]
Running WordPress 4.1.2, recently updated a couple days ago. Also running Google Analytics by Yoast Version 5.4.2, with multiple updates over the past few days. Analytics has failed to record session duration for any visit in the past two days. All sessions (which have also suddenly and suspiciously dwindled to barely any visits) reports as a "bounced" visit: 00:00:00 in session length. I haven't changed anything other than updating the plugin and wordpress version. This occurs in both Firefox and Chrome, not a browser issue. I receive no error messages, and it only started happening after updating, guessing something is not copacetic. 

Also tested this problem by having someone from another IP address visit the site, should have showed as several minute visit, recorded as 00:00:00. Multiple computers, devices, locations, etc., same thing happening across the board.

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
