### ISSUE TITLE
Add tracking to outbound links in the theme.

### ISSUE THREAD

**Issue by EHLOVader** [awesomemotive/google-analytics-for-wordpress#386]
I would like to add tracking to the outbound links (like social network links) which reside in the theme not the post content or widgets. Is there a good way to manually add these? I am trying to add the code manually using the `click` event and `__gaTracker` methods.

However I am not seeing the traffic reported.

**Comment by Rarst** [comment]
Please note that this is more on [Support](https://github.com/Yoast/google-analytics-for-wordpress#support) side and not being handled through this channel (which is primarily for reporting issues with code).

**Comment by EHLOVader** [comment]
Would it have been better to have rephrased in an accusatory way? like this?

> Yoast plugin has not tracking outbound links within the template.

If that is still a support problem I will try to make use of the WP support forum but I strongly believe that thing is where requests go to die. Usability of that thing is horrendous, especially for well established and long standing plugins like this one. 45 pages of support requests with no search, filters or [interest in implementing it](https://meta.trac.wordpress.org/ticket/7). 

*sorry just my 2¢*

**Comment by Rarst** [comment]
> Would it have been better to have rephrased in an accusatory way?

Is it ever? :)

Unfortunately that's the reality of providing free plugins. See [How can I get support?](http://kb.yoast.com/article/160-support) in knowledge base for more detailed writeup.

**Comment by EHLOVader** [comment]
I know, thank you for bearing with me.

I tried to blame myself first, I can't seem to find documentation on it but I also can't imagine I am the first to have discovered it wasn't tracking all of the links on my clients pages. I thought it would. 

A peek through the code it looks like it may never have been intended to though.

Will post in the support forum and see where it goes. 

Thanks.

**Comment by Rarst** [comment]
If you could elaborate on your use case a bit I would get a second opinion if that would make sense as a future enhancement.

**Comment by EHLOVader** [comment]
Thanks @Rarst. To explain the links I found out weren't being tracked were the outbound links in the footer to social networks, our sister sites and sometimes anything else. The themes I am working with are bespoke and don't use widgets or the nav menu structures that one might find in a purchased or distributed theme. 

I initially thought this worked on all content even the theme template content. I had previously used tools like [GAS](https://github.com/CardinalPath/gas) which work client side to hook anchor tag events and abstracts the GA script similarly to what Yoast appears to have done with __gaTracker.  However I am looking to move away from GAS because it isn't using universal analytics and appears to require quite a bit of work to make it compatible.

For reference also here is the support forum post. In case others find this and wanted to add to the conversation. 

[Wordpress Support Forum](https://wordpress.org/support/topic/outbound-links-from-the-theme-templates?replies=1)

**Comment by Rarst** [comment]
After checking in with @jdevalk we are going to consider this as future enhancement. :)

How would you expect it to work? Completely automatically? With template tag provided to be used in theme?

**Comment by EHLOVader** [comment]
I was thinking about it and I think that an automatic solution could result in more issues than it solves. Perhaps a tag or helper function that could output the handler script or anchor tag.

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
