### ISSUE TITLE
Mailto Events not working in 5.4.2 (probably stopped in 5.4) - Testing fix in REGEX

### ISSUE THREAD

**Issue by hughforsyth** [awesomemotive/google-analytics-for-wordpress#391]
Hi, 

The last mailto event I have in Analytics was 15th April 2015 (v5.3.3).  I've not seen any since 5.4 and there is no event tracking code on the mailto links in the page.

I can't see anything obviously wrong in the code.  You still seem to be trying to match mailto links.

In google-analytics-for-wordpress/frontend/abstract-class-tracking.php you seem to set the type to email based on the protocol.

```PHP
	protected function get_target_type( $extension, $domain, $origin, $matches ) {
		$download_extensions = explode( ',', str_replace( '.', '', $this->options['extensions_of_files'] ) );
		$download_extensions = array_map( 'trim', $download_extensions );
		$protocol            = $matches[3];
		$original_url        = $matches[4];

		// Break out immediately if the link is not an http or https link.
		$type = null;
		if ( $protocol !== 'http' && $protocol !== 'https' && $protocol !== 'mailto' ) {
			$type = null;
		}
		else {
			if ( ( $protocol == 'mailto' ) ) {
				$type = 'email';
			}
			elseif ( in_array( $extension, $download_extensions ) ) {
				$type = 'download';
			}
			else {
				$type = $this->parse_outbound_type( $domain, $origin, $original_url );
			}
		}

		return $type;
	}

```

And in google-analytics-for-wordpress/frontend/class-universal.php (function output_parse_link) you appear to output tracking code if type is email 

```PHP
case 'email':
				$onclick = "__gaTracker('send', 'event', 'mailto', '" . esc_js( $link['original_url'] ) . "');";
```
Perhaps this is not working as intended?
```PHP
	public function make_full_url( $link ) {
		switch ( $link['type'] ) {
			case 'download':
			case 'internal':
			case 'internal-as-outbound':
			case 'outbound':
				return $link['protocol'] . '://' . $link['original_url'];
				break;
			case 'email':
				return 'mailto:' . $link['original_url'];
				break;
		}
	}
```

But it seems that something is going wrong somewhere now.

Thanks
Hugh

**Comment by hughforsyth** [comment]
Update.  This is the REGEX not matching mailto links as it assumes :// and most mailto links include : only.

If you change the match 2 "/" to match 0 or 2 this seems to work, i.e., change {2} to {0,2}.  I've made this change on my site and it's now tracking mailto links and doesn't seem to have broken anything else.

This will match
```html
<a href="mailto:info@unitedworldschools.org?subject=Global%20Citizenship Badge Scheme Enquiry">info@unitedworldschools.org</a>
```
and
```html 
<a href="http://www.beyondthebike.org/images/my-documents/Beyond_the_Bike_Cambodia_Tour_2016.pdf" class="btn-green btn-large" target="_blank">Read the full details of the Cambodia tour (PDF)</a>
```
This is in /google-analytics-for-wordpress/frontend/abstract-class-tracking.php

```PHP
/**
	 * Regular expression for Ga.js and universal tracking to detect links
	 * @var string
	 */
	protected $link_regex = '/<a([^>]*)\shref=([\'\"])([a-zA-Z]+):(?:\/){2}?(.*)\2([^>]*)>(.*)<\/a>/isU';
```
After

```PHP
/**
	 * Regular expression for Ga.js and universal tracking to detect links
	 * @var string
	 */
	protected $link_regex = '/<a([^>]*)\shref=([\'\"])([a-zA-Z]+):(?:\/){0,2}?(.*)\2([^>]*)>(.*)<\/a>/isU';
```

**Comment by Rarst** [comment]
From quick test adjusted regex seems to work as intended. Pondering if we should throw out case with _one_ slash in between, or it's good enough.

**Comment by hughforsyth** [comment]
FWIW, I've been running the alternative REGEX in production for about 20 days without any detected issues. I've just reapplied it as the 5.4.3 update reset the REGEX.  It is still working with 5.4.3.

I haven't figured out how to do 0 or 2 slashes rather than 0,1, or 2 slashes in REGEX.  In practice this will match http:/example.com (1 slash) even though it is an invalid URL.

As an aside, it's a different issue but this doesn't match relative URLs either, e.g., "/filename.pdf" or protocol-less URLS either, e.g., "//example.com/filename.pdf".  The latter may become more common as people try and support http and https versions of sites.

**Comment by wgroenewold** [comment]
@hughforsyth The regex also works quite wel for us. I could also understand that it breaks in the cases you just spelled out. Would love to see @jrfnl crush this beast :)

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
