### ISSUE TITLE
Script is different from Google script, Google receives no data

### ISSUE THREAD

**Issue by helgatheviking** [awesomemotive/google-analytics-for-wordpress#395]
The script generated by the Yoast plugin looks different from the script suggested by Google in my analytics account.

Google's script:

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'XXXXXXXX', 'auto');
  ga('send', 'pageview');

</script>
```

The Yoast script:

```
<script type="text/javascript">

	var _gaq = _gaq || [];
	_gaq.push(['_setAccount', 'XXXXXXXX']);
	_gaq.push(['_gat._forceSSL']);
	_gaq.push(['_trackPageview']);

	(function () {
		var ga = document.createElement('script');
		ga.type = 'text/javascript';
		ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0];
		s.parentNode.insertBefore(ga, s);
	})();

</script>
```

Is there a reason for this? Could this be the reason that Google isn't getting any data from my site?

**Comment by Rarst** [comment]
I think the former is the new script, used by Universal Tracking. If your property has it enabled you'll have to enable it in plugin's settings. 

See http://kb.yoast.com/article/125-universal-analytics for details.

**Comment by lkraav** [comment]
Yes @helgatheviking you're mixing Classic and Universal here. Make sure you have Universal turned on in the plugin.

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
