### ISSUE TITLE
__gaTracker: use href title as event label

### ISSUE THREAD

**Issue by jphorn** [awesomemotive/google-analytics-for-wordpress#417]
Would it be possible to use the title tag for the onClick event instead of the actual linked word?

e.g. ```<a href="http://www.iculture.nl/app/383457673/8/Deals" onclick="__gaTracker('send', 'event', 'outbound-article-out-aff', 'http://www.iculture.nl/app/383457673/8/Deals', 'Plex - gratis');" title="Plex -  gratis" sl-processed="1">gratis</a>```

We now have a lot of nonsensical event labels which aren't really helping us. It would be great to use the title tag for this. Although I understand the title tag has lost most of it SEO value (?), it's still of great use for accessibility and reporting.

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
