### ISSUE TITLE
'Please configure your Google Analytics Settings' message

### ISSUE THREAD

**Issue by smerriman** [awesomemotive/google-analytics-for-wordpress#423]
In previous versions of the plugin, the above message would appear at the top of all admin pages when the plugin is installed/enabled but before it had been configured with a tracking ID. This was useful as a reminder tracking wasn't yet enabled, especially on development sites where this is done at a late stage.

Now the message only seems to appear on the Analytics - Dashboard page; and it actually serves no purpose there whatsoever since you already see a prompt further below.

If this was unintended, can it be restored to the previous functionality? If intended for some performance reasons, that's a shame, but in that case you might as well delete it entirely.

**Comment by smerriman** [comment]
Is this something that could be looked at? If it was unintended and you're willing to fix, I could look at making a pull request.

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
