### ISSUE TITLE
Google Analytics Dashboard Widget: $1options panel$2 

### ISSUE THREAD

**Issue by AskKim** [awesomemotive/google-analytics-for-wordpress#427]
WordPress 4.3 & Google Analytics By Yoast Version 5.4.6 

With a site authenticated to Google Analytics (and we tested by flushing it out and reconnecting it)

![Uploading 2015-09-09_21-31-38.png…]()

The Google Analytics Dashboard Widget is displaying, "You need to log in and select an account in the $1options panel$2." 

![Uploading 2015-09-09_21-30-37.png…]()

The linked text is linking to: http://www.redacteddomain.com/wp-admin/options-general.php?page=google-analytics-dashboard/gad-admin-options.php

When visiting that page, and trying to connect from there, an error is received: "Sorry, this page can't be found.  This page doesn't exist in Google Apps Administrator Help. It may be deleted because the feature doesn't exist anymore, or the URL may be incorrect.""

The destination URL one reaches, with the above error, after attempting to connect is this: https://support.google.com/a/answer/6224347?p=oauth&rd=1

We tested for a plugin/theme conflict and did not find any. The problem persists in a default theme with all plugins deactivated except the Google Analytics Dashboard and the Google Analytics by Yoast plugin.

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
