### ISSUE TITLE
Tooltip not entirely visible

### ISSUE THREAD

**Issue by andizer** [awesomemotive/google-analytics-for-wordpress#430]
When hovering the question mark for the sessions I discover the tooltip isn't completely visible.

![yoast_google_analytics__dashboard_ _theme_ _wordpress](https://cloud.githubusercontent.com/assets/325040/9899767/6821950a-5c5c-11e5-869f-75575fd17721.png)

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
