### ISSUE TITLE
Weird notice when deactivating-activating plugin

### ISSUE THREAD

**Issue by andizer** [awesomemotive/google-analytics-for-wordpress#431]
I look likes my data will be cleared when I deactivate my plugin, because I get the following notice after activating the plugin:

![yoast_google_analytics__dashboard_ _theme_ _wordpress](https://cloud.githubusercontent.com/assets/325040/9904730/5bec3d20-5c80-11e5-85e4-04b4e50c99a1.png)

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
