### ISSUE TITLE
All tabs are broken!

### ISSUE THREAD

**Issue by ve3** [awesomemotive/google-analytics-for-wordpress#433]
Analytics > Dashboard > click on any tabs > not working
Analytics > Settings > click on any tabs > not working

I have....
WP **4.3.1**
**Google Analytics by Yoast 5.4.6**
Yoast SEO 2.3.5
It is GA by Yoast problem.

Look in Firebug console and found these errors on Analytic dashboard and settings page.

    admin.php?page=yst_ga_dashboard (line 253, col 5)
    ReferenceError: dimension_switch is not defined
    dimension_switch(element); 

...

    admin.php?page=yst_ga_settings (line 273)
    TypeError: jQuery(...).chosen is not a function
    jQuery('#yoast-ga-form-select-settings-analytics_profile').chosen({

**Comment by nhylated** [comment]
Do you have uBlock or any other similar extension installed in your browser? Can you try disabling those extensions and then opening the plugins pages again?

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
