### ISSUE TITLE
Outline advanced settings should be fixed

### ISSUE THREAD

**Issue by CarolineGeven** [awesomemotive/google-analytics-for-wordpress#435]
The dropdown for 'Track full URL of outbound clicks or just the domain: should be outlined the same as the other textfields and dropdowns. Right now it's aligned strange because it doesn't have a tooltip.

![schermafbeelding_2015-10-01_om_14_45_22](https://cloud.githubusercontent.com/assets/8614579/10220924/2109df9c-684b-11e5-966a-7577c0ada087.png)

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
