### ISSUE TITLE
Be able to create a refresh token on the front end.

### ISSUE THREAD

**Issue by christophercochran** [awesomemotive/google-analytics-for-wordpress#436]
Currently if you are using Yoast_Google_Analytics::get_instance()->do_request() on the front end, it won't be able to do a request without triggering a refresh token by visiting the dashboard. There should be a way to trigger this token refresh and send it out with a request if making a call from the front end.

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
