### ISSUE TITLE
Setting up custom event

### ISSUE THREAD

**Issue by isaumya** [awesomemotive/google-analytics-for-wordpress#437]
Hey guys can anyone help me out about how to do custom even tracking while using this plugin? I'm adding custom code via jquery depending on adblcoking enabled like this

`_gaq.push(['_trackEvent', 'Adblock', 'Blocked', 'false',,true])`

But what I'm more worried about is whether or not `_gaq.push` will work out of the box, should I have to enable something on settings?

Currently,
this is my universal tab - http://puu.sh/kzLnj/570ba6e165.png
This is my advanced tab - http://puu.sh/kzLqr/205239bdfd.png

Should I have to enable something else too? Please let me know.

**Comment by ChrisHurrell** [comment]
I have spent the last few days trying to get custom event tracking to work with this plugin on a client site (universal analytics), using the link syntax: 

<a href="#" onclick="ga('send', 'event', 'Publication', 'Download', 'PDF Title');">Download as PDF</a>

It doesn't show any events being tracked. The plugin does, however track all other non-custom events.

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
