### ISSUE TITLE
safety-privacy issue: settings visible from non admin users?

### ISSUE THREAD

**Issue by Elan42** [awesomemotive/google-analytics-for-wordpress#438]
Normal users, (my custom user called "customer") can view and edit settings !
Isn't that terrible? is there a hook to fix that with capability editing ?

I want only my admin user to do that !
I have > 40 analytics accounts in my google analytics page and I don't want my customer to see them !

**Comment by Rarst** [comment]
What user role do they have? How is it set up?

**Comment by Elan42** [comment]
if (run_once('add_user_role')) {
        remove_role('client');
        add_role('client', 'Client', array(
                'edit_theme_options' => true,
                'edit_dashboard' => true,
                'moderate_comments' => true,
                'manage_categories' => true,
                'manage_links' => true,
                'unfiltered_html' => true,
                'edit_others_posts' => true,
                'edit_pages' => true,
                'edit_others_pages' => true,
                'edit_published_pages' => true,
                'publish_pages' => true,
                'delete_pages' => true,
                'delete_others_pages' => true,
                'delete_published_pages' => true,
                'delete_others_posts' => true,
                'delete_private_posts' => true,
                'edit_private_posts' => true,
                'read_private_posts' => true,
                'delete_private_pages' => true,
                'edit_private_pages' => true,
                'read_private_pages' => true,
                'edit_published_posts' => true,
                'upload_files' => true,
                'publish_posts' => true,
                'delete_published_posts' => true,
                'edit_posts' => true,
                'delete_posts' => true,
                'edit_theme_options' => true,
                'read' => true,
                'NextGEN Gallery overview' => false,    //
                'NextGEN Use TinyMCE' => true,
                'NextGEN Upload images' => true,
                'NextGEN Manage gallery' => true,
                'NextGEN Manage others gallery' => true,
                'NextGEN Manage tags' => true,
                'NextGEN Edit album' => true,
                'NextGEN Change options' => false,      //
                'NextGEN Change style' => false,        //

                'manage_woocommerce' => true,
                'manage_woocommerce_orders' => true,
                'manage_woocommerce_coupons' => true,
                'manage_woocommerce_products' => true,
                'view_woocommerce_reports' => true,
                'shop_manager' => true,

                'wpcf7' => false,                       //
                'wpcf7-new' => false,                   //

                'shortcodes-ultimate-examples' => false,//
                'shortcodes-ultimate-addons' => false,  //


                'gadash_backend_settings' => true,
                'wpml-string-translation' => false,
                'ga_display_level' => true,


                'wpseo_xml' => true,
                'wpseo_bulk_edit' => true,

                'wysija_campaigns' => true,
                'wysija_subscribers' => true,
                'wysija_newsletters' => true,
                'wysija_config' => false                //
));

**Comment by Rarst** [comment]
Can you replicate the issue with one of native WP roles?

Not sure on top of my head which cap it needs, but it's probably `manage_options`... I will take a more thorough look later.

**Comment by Rarst** [comment]
Cannot reproduce with native Editor role.

**Comment by Elan42** [comment]
This is the code with wich I create the user:
if (run_once('add_user_role')) {
        add_role('cliente', 'Cliente', array(
                'edit_theme_options' => true,
                'edit_dashboard' => true,
                'moderate_comments' => true,
                'manage_categories' => true,
                'manage_links' => true,
                'unfiltered_html' => true,
                'edit_others_posts' => true,
                'edit_pages' => true,
                'edit_others_pages' => true,
                'edit_published_pages' => true,
                'publish_pages' => true,
                'delete_pages' => true,
                'delete_others_pages' => true,
                'delete_published_pages' => true,
                'delete_others_posts' => true,
                'delete_private_posts' => true,
                'edit_private_posts' => true,
                'read_private_posts' => true,
                'delete_private_pages' => true,
                'edit_private_pages' => true,
                'read_private_pages' => true,
                'edit_published_posts' => true,
                'upload_files' => true,
                'publish_posts' => true,
                'delete_published_posts' => true,
                'edit_posts' => true,
                'delete_posts' => true,
                'edit_theme_options' => true,
                'read' => true,

                'wpseo_xml' => true,
                'wpseo_bulk_edit' => true,
                'gadash_backend_settings' => true,
                'wpml-string-translation' => false,
                'ga_display_level' => true,
                'manage_woocommerce' => true,
                'manage_woocommerce_orders' => true,
                'manage_woocommerce_coupons' => true,
                'manage_woocommerce_products' => true,
                'view_woocommerce_reports' => true,
                'shop_manager' => true,
                'wysija_campaigns' => true,
                'wysija_subscribers' => true,
                'wysija_newsletters' => true,
}

It works with all plugins ...

Do you have some custom capability to add to the user creation ?


2015-10-21 11:53 GMT+02:00 Andrey Savchenko <notifications@github.com>:

> Cannot reproduce with native Editor role.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Yoast/google-analytics-for-wordpress/issues/438#issuecomment-149842000>
> .
>



-- 
Alvise Nicoletti
ELAN42///
network communication
///
+393401476103
webmaster@elan42.com
///
www.ELAN42.com


///
Il presente messaggio ed ogni eventuale documento allegato potrebbe
contenere informazioni riservate e confidenziali. Qualora non foste il
destinatario Vi preghiamo di avvertire immediatamente il mittente e
cancellare il messaggio. Ogni altro uso di questa email, inclusa
la duplicazione e la divulgazione del contenuto, è proibito.

This message and any file transmitted with it may contain privileged
or confidential information. In case you were not listed in the adressed
recipient, please notify the sender immediately and delete the message. Any
other use of this email, including copying it and the disclosure of its
content, is prohibited. <http://www.elan42.com>

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
