### ISSUE TITLE
Mixup with single quoted onclicks

### ISSUE THREAD

**Issue by andizer** [awesomemotive/google-analytics-for-wordpress#441]
When having an onclick attributes on an anchor there will be a mixup with the onclick event we are adding. 

Example:
`<a href='http://domain.dev' onclick='alert(123);'>With an onclick event, single quoted</a>`

Will become:
`<a href="http://domain.dev" onclick='alert(123); __gaTracker('send', 'event', 'outbound-article', 'http://domain.dev', 'With an onclick event, single quoted');'>With an onclick event, single quoted</a><br />`

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
