### ISSUE TITLE
Onclick went wrong when function in onclick isn't closed properly.

### ISSUE THREAD

**Issue by andizer** [awesomemotive/google-analytics-for-wordpress#442]
When calling an onclick event which isn't closed properly (`;`). The onclick event will be added as a second attribute instead of being merge with the event we are adding.

Example:
`<a href='http://nu.nl' onclick="alert(123)">With an onclick event, without closing the function.</a>`

Result:
`<a href="http://nu.nl" onclick="__gaTracker('send', 'event', 'outbound-article', 'http://nu.nl', 'With an onclick event, without closing the function.');" onclick="alert(123)">With an onclick event, without closing the function.</a>`

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
