### ISSUE TITLE
Strange behaviour when attributes contains html

### ISSUE THREAD

**Issue by andizer** [awesomemotive/google-analytics-for-wordpress#443]
When attributes contains HTML there is some strange behaviour.

Input:
`<a href='http://nu.nl' title='<b>Hoi</b>'>With an anchor given in the method.</a>`

Output:
`<a href="http://nu.nl" onclick="__gaTracker('send', 'event', 'outbound-article', 'http://nu.nl', 'Hoi&#8216;&gt;With an anchor given in the method.');" title='<b>Hoi</b>&#8216;>With an anchor given in the method.</a>`

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
