### ISSUE TITLE
Having two tours might be confusing

### ISSUE THREAD

**Issue by andizer** [awesomemotive/google-analytics-for-wordpress#445]
When I didn't ignore the tour for Analytics and I have SEO installed without ignoring the tour also, I get two start tour popups which might be a little bit confusing:
![dashboard_ _theme_ _wordpress](https://cloud.githubusercontent.com/assets/325040/10817326/55e51ec6-7e39-11e5-8aef-fd69a588256f.png)

It is not clear which window belongs to which tour without reading the paragraphs.
![yoast_google_analytics__settings_ _theme_ _wordpress](https://cloud.githubusercontent.com/assets/325040/10817302/314a8556-7e39-11e5-928c-943a162daf9b.png)

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
