### ISSUE TITLE
[Feature Request] Remove Subdomain tracking

### ISSUE THREAD

**Issue by amboutwe** [awesomemotive/google-analytics-for-wordpress#448]
Per the [guidelines](https://developers.google.com/analytics/devguides/collection/analyticsjs/cross-domain), subdomain tracking is no longer needed.

"Tracking users across subdomains does not require any additional configuration."

![image](https://cloud.githubusercontent.com/assets/8060612/10852272/8e0de4b0-7ef5-11e5-8409-0e8ae1751e38.png)

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
