### ISSUE TITLE
[Feature Request] Support for Master Accounts in GA

### ISSUE THREAD

**Issue by blondishnet** [awesomemotive/google-analytics-for-wordpress#449]
(Refers to client in HelpScout ticket #81764)

Client runs an agency that is in charge of many accounts. When the end-user adds their GA account to the plugin, and has a master account (manages multiple GA websites), those websites are still available for other admins to see.

This is not just the drop down they are seeing, but also able to access and view analytics in the plug's dashboard. Because I manage several GA accounts, I confirmed that this is indeed happening (in my own website's backend), and can be accessed by others with administrator level status.

Discussed with @amboutwe through Slack about this, and in the past, it seems we were telling people that they should use an individual account, not a "master" account.

Feature request is for supporting master accounts:

1. Locking out other GA accounts from being seen from that website once a profile has been selected

2.  Or prevent other GA accounts from at least being accessed without prompt to re-login to GA in order to make changes.

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
