### ISSUE TITLE
Start tour box does not stay with the Analytics menu item while scroling

### ISSUE THREAD

**Issue by diedexx** [awesomemotive/google-analytics-for-wordpress#451]
Gif (might take a while):
![scroll tour](https://cloud.githubusercontent.com/assets/5352634/10997820/a473b82e-8490-11e5-9af2-2204d49c5f56.gif)

Used:
- GA trunk 
- WordPress v4.3.1

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
