### ISSUE TITLE
Plug-in not working, different script

### ISSUE THREAD

**Issue by Moszkowicz** [awesomemotive/google-analytics-for-wordpress#454]
Hi,

I used this plugin for multiple websites, but at some point one of the websites couldn't be tracked anymore. I try to find the issue, because for other websites it still worked. I compared the websites and saw a small difference:

This is the script of the website that can't tracked:
```
<script type="text/javascript">
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','//www.google-analytics.com/analytics.js','__gaTracker');

	__gaTracker('create', 'UA-47738332-1', 'auto');
	__gaTracker('set', 'forceSSL', true);
	__gaTracker('send','pageview');

</script>
```
And this is a script from a website that is being tracked:
```
<script type="text/javascript"> 
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){ 
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o), 
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m) 
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga'); 
ga('create', 'UA-43901762-2', '4cargo.nl'); 
ga('send', 'pageview'); 
</script>
```
I tried to reinstall the plugin on the website that can't be tracked but it didn't work.
I waited for an update to see if the problem would be resolved, but after updating it the problem is still there..

Is there a way for me to fix the problem?

**Comment by Rarst** [comment]
Could you please provde example URL of a live site with the issue?

**Comment by Moszkowicz** [comment]
The url of the website with the issue is http://www.assinkonline.nl

**Comment by Rarst** [comment]
Not sure what the issue is. I had tried your site with [GA Debugger](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna/related?hl=en) extension for Chrome and it reports what seems to be the normal for it:

```
Running analytics_debug.js. This script is intended for testing and debugging only.
Initializing Google Analytics.
Running command: ga("create", "UA-47738332-1", "auto")
Creating new tracker: t0
New visitor. Generating new clientId
Auto cookieDomain found: "assinkonline.nl"
Running command: ga("set", "forceSSL", true)
Running command: ga("send", "pageview")
Setting throttling cookie: "_gat"

Sent beacon:
v=1&_v=j40d&a=426952326&t=pageview&_s=1&dl=http%3A%2F%2Fwww.assinkonline.nl%2F&ul=ru&de=UTF-8&dt=Assink%20Pure%20Identity%20%7C%20k…d=1432580418&cid=1419030994.1448629981&tid=UA-47738332-1&_r=1&z=1001250649


_j1              (&jid) 1432580418
adSenseId        (&a)   426952326
apiVersion       (&v)   1
clientId         (&cid) 1419030994.1448629981
encoding         (&de)  UTF-8
flashVersion     (&fl)  19.0 r0
hitType          (&t)   pageview
javaEnabled      (&je)  1
language         (&ul)  ru
location         (&dl)  http://www.assinkonline.nl/
screenColors     (&sd)  24-bit
screenResolution (&sr)  1080x1920
title            (&dt)  Assink Pure Identity | kapsalon en schoonheidssalon
trackingId       (&tid) UA-47738332-1
viewportSize     (&vp)  1080x958
```

**Comment by Moszkowicz** [comment]
Yeah I also tried that and it gave me the same results. But when I open Google Analytics it says that it cannot track the website. Is there any way for me to change the script within the plugin so that it is the same as the other website?

**Comment by Rarst** [comment]
I am not very familiar with GA plugin, so don't know where the difference comes from.

Looking at my own site I see the former version of the script snippet and it works just fine for me.

Is it possible you have some kind of setup issue on GA side?

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
