### ISSUE TITLE
Sales goals and transactions don't match WooCommerce order

### ISSUE THREAD

**Issue by galbaras** [awesomemotive/google-analytics-for-wordpress#455]
I used GA eCommerce tracking to track WooCommerce performance and neither my sales goals not the number of ecommerce transactions match what WooCommerce shows as the number of orders.

In case this makes any difference, I run the following custom code (optimizely doesn't work otherwise):

`// Make sure the correct tracking function is called by non-WordPress scripts`
`var ga = typeof ga === "undefined" ? __gaTracker : ga;`
`// Optimizely Universal Analytics Integration`
`window.optimizely = window.optimizely || [];`
`window.optimizely.push("activateUniversalAnalytics");`
`// End Optimizely integration`

Any idea how to crack this thing?

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
