### ISSUE TITLE
Unreliable link events due to race condition

### ISSUE THREAD

**Issue by oxyc** [awesomemotive/google-analytics-for-wordpress#456]
I just reviewed some code and it looks like you're not using the GA `hitCallback` functionality when you track events on links. This causes a race condition where the browser might redirect before the pixel request has been issued.

https://support.google.com/analytics/answer/1136920?hl=en&rd=1

Possibly related issues:
- #333 
- https://wordpress.org/support/topic/download-tracking-events-not-working

**Comment by oxyc** [comment]
For reference this is how the Drupal Google Analytics module solved this (using beacon and `mousedown`, `touchstart`, `keyup` events.

https://www.drupal.org/node/1580144#comment-7958641

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
