### ISSUE TITLE
Save button of settings page returns console error

### ISSUE THREAD

**Issue by boblinthorst** [awesomemotive/google-analytics-for-wordpress#457]
When you press the save button on the settings page (any tab), it returns an error in the console. 

The error might not even break anything, seeing as everything seems to work fine, but it does make you question why the error is there. 

error is:
Uncaught TypeError: Cannot read property 'close' of undefined
yst_closepopupwindow @ yoast_ga_admin.min.js?ver=5.4.6:1
onclick @ admin.php?page=yst_ga_settings:267
Navigated to http://local.wordpress.dev/wp-admin/admin.php?page=yst_ga_settings

steps to reproduce:

1. navigate to the settings page of GA
2. open your console (alt+cmd+i and press the console tab). 
3. check the preserve log checkbox. 
4. click the save changes button. 

Without checking the preserve log checkbox, the error is only visible for a fraction of a second. 

![issue_29](https://cloud.githubusercontent.com/assets/11849359/11687826/37ca41e4-9e89-11e5-8379-8ecc820d145d.png)

<hr>

__Tested on:__

WordPress version 4.3.1 (multisite subdomain).
GA 5.4.6

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
