### ISSUE TITLE
Analytics Code not Appearing in Source

### ISSUE THREAD

**Issue by KadenLag** [awesomemotive/google-analytics-for-wordpress#458]
Plugin is fully up to date, I have synced with my account and it can see the code fine in the admin area but when viewing the source code i cant find the code anywhere.

tested with the all in one seo plugin as well, when using that it inserts the code fine.

http://prntscr.com/9cj8a4   (admin backend)
http://prntscr.com/9cj6oi (source view)

**Comment by bhubbard** [comment]
It looks like you have it set to not track admins and editors, try viewing the source code logged out of the site.

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
