### ISSUE TITLE
Outbound link tracking breaking inline script

### ISSUE THREAD

**Issue by danielmilner** [awesomemotive/google-analytics-for-wordpress#466]
I have a client who has an inline **script** to display a street map. The outbound link tracking appears to be rewriting a URL in this script to track the link, but it is causing a JavaScript error.

These are the lines that are being rewritten: (Notice the **onclick** in the attribution link)
```
// add an OpenStreetMap tile layer
L.tileLayer('http://{s}.tiles.wmflabs.org/bw-mapnik/{z}/{x}/{y}.png', {
	attribution: '&copy; <a href="http://osm.org/copyright" onclick="__gaTracker('send', 'event', 'outbound-article', 'http://osm.org/copyright', 'OpenStreetMap');">OpenStreetMap</a> contributors'
}).addTo(map);
```

Here is the URL where you can see the issue:
http://christcommunitykc.org/calendar-of-events/event-details/?ccbpress_event_id=3544

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
