### ISSUE TITLE
Block Ghost Spam in Google Analytics

### ISSUE THREAD

**Issue by bhubbard** [awesomemotive/google-analytics-for-wordpress#469]
Hey guys,

We notice we have been battling ghost spam more and more, and want to know if there is anything we can do in this plugin to help battle it. We use your plugin for all of our client sites, so anything we can do at this plugin level would help tremendously. 

Maybe we can use the Google API to create filters for ghost spam? 

Other Resources about Ghost Spam:
https://moz.com/blog/stop-ghost-spam-in-google-analytics-with-one-filter
https://github.com/devimweb/bot-public-list
http://www.ohow.co/what-is-referrer-spam-how-stop-it-guide/
https://github.com/devimweb/bot-public-list
https://wordpress.org/plugins/wp-block-analytics-spam/
https://www.adwordsrobot.com/en/tools/ga-referrer-spam-killer

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
