### ISSUE TITLE
Update URLS to HTTPS

### ISSUE THREAD

**Issue by bhubbard** [awesomemotive/google-analytics-for-wordpress#476]
Doing a quick search on the plugin, you find many urls link to sites that now support or default to `https://`. These links should get updated. Here is an example search:

https://github.com/awesomemotive/google-analytics-for-wordpress/search?utf8=%E2%9C%93&q=http%3A%2F%2F

Here are a few domains that have links that can be updated fairly quickly with a **careful** find and replace:

* http://make.wordpress.org
* http://wordpress.org
* http://translate.yoast.com
* http://getharvest.com
* etc

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
