### ISSUE TITLE
Support for CodeClimate

### ISSUE THREAD

**Issue by bhubbard** [awesomemotive/google-analytics-for-wordpress#477]
CodeClimate is free for open source projects, and now supports WordPress standards for PHPCodeSniffer. It would be create to create a config file.

Repo on CodeClimate
https://codeclimate.com/github/awesomemotive/google-analytics-for-wordpress

Example .codeclimate.yml
https://docs.codeclimate.com/docs/example-codeclimateyml

PHP Code Sniffer config instructions:
https://github.com/codeclimate/codeclimate-phpcodesniffer

**Comment by chriscct7** [comment]
We're look into using services as we move forward. We'll likely end up simplifying things to just Scrutinizer but we're currently comparing many many different services.

https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
