### ISSUE TITLE
Track Jetpack Social Share Buttons

### ISSUE THREAD

**Issue by bhubbard** [awesomemotive/google-analytics-for-wordpress#478]
It would be great for sites that use`jetpack`, if `google-analytics-for-wordpress` could add some extra tracking for the social share links.

https://jeremy.hu/jetpack-add-utm-tracking-to-sharing-buttons/
http://www.statstory.com/social-tracking-with-wordpress-jetpack-google-analytics/
http://www.bloggerzarena.com/track-social-share-and-traffic-using-jetpack/

**Comment by chriscct7** [comment]
https://github.com/awesomemotive/google-analytics-for-wordpress/issues/479
