### ISSUE TITLE
is there a way to exclude google analytics code on a specific URL?

### ISSUE THREAD

**Issue by halukkaramete** [awesomemotive/google-analytics-for-wordpress#482]
Is it possible to this? is there a way to exclude google analytics code on a specific URL?

We could not see a config option to do this.

Is there a hook that you can recommend for us to solve our issue?

Thank you

**Comment by chriscct7** [comment]
Hi there,
No there's not an option for this in the panel. I'm curious as to why you want to exclude a URL.

Right now, there's not a hook in the current version that'd be useful for this, however in the 6.0 release coming up you could use the one for disabling the analytics/events output. 

Also you can always block statistics for a specific URL in Google Analytics using an exclude filter on a view.
