### ISSUE TITLE
Add filter to display attributes in GA script

### ISSUE THREAD

**Issue by chvillanuevap** [awesomemotive/google-analytics-for-wordpress#484]
Hi!

I'm using the [Rocket Loader](https://support.cloudflare.com/hc/en-us/articles/200168056-What-does-Rocket-Loader-do-) module provided by [Cloudflare](https://www.cloudflare.com). Rocket Loader is an asynchronous JavaScript loader that my website uses to improve its loading time.

The module rewrites all script tags as `<script type="text/rocketscript">`. This does not affect the GA code from collecting the correct statistics, but it does prevent the correct functioning of the Google Tag Assistant and the Google In-Page Analytics plugins on Google Chrome.

You can have Rocket Loader ignore individual scripts by adding the `data-cfasync="false"` attribute to the relevant script tag, for example: `<script data-cfasync="false" src="/file.js"></script>`.

I would like to suggest a filter in your plugin to allow the users to add additional attributes to the GA script tags. For example, in `frontend/views/tracking-universal.php`, we could modify the script tag to the following:

```
<script type="text/javascript" <?php echo gawp_attr( apply_filters( 'gawp-script-attr', array(), $context = 'universal' ) ) ?> >
```

Where  `gawp_attr` is a function used to sanitize the input:

```
function gawp_attr( $attributes = array() ) {

	$output = '';

	// Cycle through attributes, build tag attribute string.
	foreach ( $attributes as $key => $value ) {

		if ( ! $value ) {
			continue;
		}

		if ( true === $value ) {
			$output .= esc_html( $key ) . ' ';
		} else {
			$output .= sprintf( '%s="%s" ', esc_html( $key ), esc_attr( $value ) );
		}

	}

	return trim( $output );

}
```

The user can then add attributes at will with the `gawp-script-attr` filter:

```
add_filter( 'gawp-script-attr', function( $attributes, $context ) {

	$key = 'data-cfasync';
	$value = 'false';

	$attributes[$key] = $value;

	return $attributes;

}, 10, 2 );
```

Cloudflare is a very popular service, so I'm sure a lot of people have encountered this issue. It is not a major problem as the analytics are correct with or without the `data-cfasync` attribute. However, being able to turn off Rocket Loader for these scripts in order to use the Tag Assistant and the In-Page Analytics plugins to get more insight into the behavior of our visitors would be invaluable!

Let me know what you think, and thanks for your attention!

Hernan

**Comment by chriscct7** [comment]
Thanks for the suggestion @chvillanuevap!

The `data-cfasync` attribute is output on the frontend <script> tags in the upcoming MonsterInsights 6.0 release.

**Comment by chvillanuevap** [comment]
Thanks for the reply, Chris! 

If you don't mind me asking, are you going to hardcode the `data-cfasync` attribute in the script tag, or are you going to provide a filter? While hardcoding the attribute is a nice hands-off solution for me, I believe providing a filter offers more robustness and flexibility to the user; for example, in case Cloudflare decides to change the attribute name in the future, or a different user needs a different attribute name for a very different problem.

Either way, thank you for giving some time to my request! I truly appreciate it!

**Comment by chriscct7** [comment]
Not a problem!

For now, we're not going to introduce another filter, because post-6.0 we want to rework the frontend output one more time (at 6.1.0 when we consider removing the deprecated ga.js support). For this reason, we're not adding too many filters, so that we can fully backwards-compatibly support all of the existing ones that will be in 6.0. It is our goal however to make the plugin's frontend output as easily extendable as possible to allow for exactly that ^ (change of name or additional attributes).

**Comment by chvillanuevap** [comment]
Perfectly reasonable! Thanks a lot for taking the time to explain the issue to me!

**Comment by chriscct7** [comment]
Not a problem!
