### ISSUE TITLE
ga script still added after I removed the plugin

### ISSUE THREAD

**Issue by xHeliotrope** [awesomemotive/google-analytics-for-wordpress#486]
So I deactivated the plugin and removed it, and the analytics tag is still being added to my site(after the footer). Do I need to remove some script script in functions or footer to remove the script entirely?

**Comment by chriscct7** [comment]
Hi there,
When the plugin is removed the script can't be being output from MonsterInsights as it no longer exists. 

If it's still being output one of two things are happening. If the comment code surrounding the script says MonsterInsights your site likely uses either server-side or a plugin based cashing system similar to WP total cache or WP super cache or WP rocket cache. This cache will need to be cleared.

If it is not surrounded by such a comment then the ga script is being output from another source.

**Comment by chriscct7** [comment]
Also if the analytics script is after the footer, it's not MonsterInsights as we put it in the `<head>` section of the document as recommended by Google
