### ISSUE TITLE
Differentiate Between "Regular Views from Facebook" and "FB Instant Articles Views"

### ISSUE THREAD

**Issue by ibnusaheed** [awesomemotive/google-analytics-for-wordpress#491]
The other day as we discussed, I think it would be AWESOME if users can easily differentiate between regular article views from Facebook and FB Instant Articles views. Currently, both views are combined in the report, which makes it difficult for users to optimize the page for Instant Articles, and track whether their optimization efforts are bringing any result.

**Comment by chriscct7** [comment]
Tracked in Asana
