### ISSUE TITLE
I'm getting this error

### ISSUE THREAD

**Issue by cgcullen** [awesomemotive/google-analytics-for-wordpress#493]
Error Level: E_ERROR
Message: Uncaught Error: Call to undefined function get_user_count() in /www/mdm/public/wp-content/plugins/google-analytics-for-wordpress/includes/admin/tracking.php:74 Stack trace: #0 /www/mdm/public/wp-content/plugins/google-analytics-for-wordpress/includes/admin/tracking.php(121): MonsterInsights_Tracking->get_data() #1 /www/mdm/public/wp-includes/class-wp-hook.php(286): MonsterInsights_Tracking->send_checkin() #2 /www/mdm/public/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #3 /www/mdm/public/wp-includes/plugin.php(515): WP_Hook->do_action(Array) #4 /www/mdm/public/wp-cron.php(126): do_action_ref_array('monsterinsights...', Array) #5 {main} thrown
File: /www/mdm/public/wp-content/plugins/google-analytics-for-wordpress/includes/admin/tracking.php
Line: 74

**Comment by cgcullen** [comment]
Any help?

**Comment by jaygidwitz** [comment]
Hi There, Thanks for reaching out! Can you please create a ticket at https://www.monsterinsights.com/lite-support/ so that we can investigate?
