### ISSUE TITLE
Is there a constant or filter to disable sending data to GA on a staging or dev site

### ISSUE THREAD

**Issue by lukecav** [awesomemotive/google-analytics-for-wordpress#499]
I am trying to find if there is a filter or a constant in the plugin which can be used to disable the plugin from sending data to Google Analytics if the plugin is still active and is copied over on a staging or a regression testing site?

**Comment by chriscct7** [comment]
Not currently, but we can add one in the next release as `MONSTERINSIGHTS_DISABLE_TRACKING`.
