### ISSUE TITLE
Please push your version 7.10.4 changes

### ISSUE THREAD

**Issue by jan-lukowiak** [awesomemotive/google-analytics-for-wordpress#500]
Hi,
thank you for your work and providing this awesome plugin to us. Please update this repo to version 7.10.4 and push your most recent changes. Last version in this repo is 7.10.3.
Thank you in advance,
Jan

**Comment by chriscct7** [comment]
Hi there!
We'll look into that and make sure it happens with our upcoming next release. The change pushes should be automatic with our workflow that we use.
