### ISSUE TITLE
Borlabs Cookie is not able to scan mi_version-script-blog for script blocker

### ISSUE THREAD

**Issue by j0nnybrav079** [awesomemotive/google-analytics-for-wordpress#503]
**The bug**
When trying to add a script-blocker, as described here: https://de.borlabs.io/kb/monsterinsights-nutzen-script-blocker/
Borlab is not able to find the MonsterInsights block. I am not sure if this is a MI-bug, or a Borlabs bug.

**To Reproduce**
1. Go to WP-Backend -> Borlabs Cookie -> Script Blocker
2. Click on "New", 
3. Select on of your pages, you are sure to have the block in the source code
4. as queries type "mi_version"
5. Click on scan 
6. -> the scanner is not able to find the block

I already disabled any caching and any roles as described in the tutorial.

** the question **
So why is Borlab not able to finde the block in the source-code?

**Comment by chriscct7** [comment]
This is a Borland bug as we don't integrate with them, so whatever their scanner is doing must have a bug in it.
